apiVersion: v1
kind: Service
metadata:
  name: practice-svc
  labels:
    app: practice
spec:
  type: NodePort
  ports:
  - port: 8080
    name: practice
    targetPort: 8080
    nodePort: 30008
    protocol: TCP
  selector:
    app: practice
