apiVersion: v1
kind: Pod
metadata:
  name: practice
  labels:
    app: practice
spec:
  containers:
    - name: practice
      image:  caoxunaaa/practice:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
