apiVersion: v1
kind: Service
metadata:
  name: user-rpc-cs
  namespace: superxon
  labels:
    app: user-rpc
spec:
  type: NodePort
  ports:
  - port: 8080
    name: user-rpc-cs
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: user-rpc
