apiVersion: v1
kind: Service
metadata:
  name: beanstalkd
  namespace: superxon
spec:
  selector:
    app: beanstalkd
  type: NodePort
  ports:
  - name: beanstalkd-1
    port: 11300
    targetPort: 11300
    nodePort: 31300
    protocol: TCP
  - name: beanstalkd-2
    port: 11301
    targetPort: 11300
    nodePort: 31301
    protocol: TCP
