apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-1
  namespace: superxon
spec:
  serviceName: kafka-hs-1
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
      - name: kafka-1
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-hs-1.superxon.svc.cluster.local
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1.superxon.svc.cluster.local:2181,zoo2.superxon.svc.cluster.local:2181,zoo3.superxon.svc.cluster.local:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: mytopic:2:1
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://172.20.3.13:30901
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        volumeMounts:
        - name: datadir
          mountPath: /var/run
      volumes:
        - name: datadir
          nfs:
            server: 172.20.3.13
            path: /usr/local/k8s/kafka/pv01     
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-2
  namespace: superxon
spec:
  serviceName: kafka-hs-2
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
      - name: kafka-2
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-hs-2.superxon.svc.cluster.local
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1.superxon.svc.cluster.local:2181,zoo2.superxon.svc.cluster.local:2181,zoo3.superxon.svc.cluster.local:2181
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_CREATE_TOPICS
          value: mytopic:2:1
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://172.20.3.13:30902
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        volumeMounts:
        - name: datadir
          mountPath: /var/run
      volumes:
        - name: datadir
          nfs:
            server: 172.20.3.13
            path: /usr/local/k8s/kafka/pv02
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-3
  namespace: superxon
spec:
  serviceName: kafka-hs-3
  replicas: 1
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
        app: kafka-3
    spec:
      containers:
      - name: kafka-3
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-hs-3.superxon.svc.cluster.local
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1.superxon.svc.cluster.local:2181,zoo2.superxon.svc.cluster.local:2181,zoo3.superxon.svc.cluster.local:2181
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_CREATE_TOPICS
          value: mytopic:2:1
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://172.20.3.13:30903
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        volumeMounts:
        - name: datadir
          mountPath: /var/run
      volumes:
        - name: datadir
          nfs:
            server: 172.20.3.13
            path: /usr/local/k8s/kafka/pv03

