apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: device-base-gateway
  namespace: superxon
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: grpc
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: device
  namespace: superxon
spec:
  hosts:
  - "*"
  gateways:
  - device-base-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: grpc-device-base-rpc
        port:
          number: 8080
